# ── Site + theme ───────────────────────────────────────────────────────────────
version: 2
name: "Zhang Gaofei"
title: "PhD Student in Higher Education, Xiamen University (2023–Present)"
email: "lambda2046@outlook.com"

remote_theme: sproogen/modern-resume-theme
plugins:
  - jekyll-remote-theme

darkmode: auto   # auto / true / false

# Optional header links (edit later)
social_links:
  - title: Google Scholar
    icon: fas fa-graduation-cap
    url: https://scholar.google.com/citations?user=YOUR_ID
  - title: ORCID
    icon: fab fa-orcid
    url: https://orcid.org/0000-0000-0000-0000
  - title: GitHub
    icon: fab fa-github
    url: https://github.com/YOUR_USERNAME
  - title: LinkedIn
    icon: fab fa-linkedin
    url: https://www.linkedin.com/in/YOUR_USERNAME/

additional_links:
  - title: CV (PDF)
    icon: fas fa-file-pdf
    url: /assets/Zhang_Gaofei_CV.pdf

# If you add a profile photo later:
# about_profile_image: assets/profile.jpg

# ── Page content ───────────────────────────────────────────────────────────────
content:
  - title: About
    layout: text
    content: |
      <!-- 2–4 sentences: your identity, focus, and current work. -->
      <!-- Example placeholder (replace later): -->
      I am an academic practitioner and PhD student in Higher Education at Xiamen University (2023–Present).
      My work centers on student development, academic vocational education, and informationization in education.

  - title: Research Interests
    layout: text
    content: |
      • Student Development  
      • Academic Vocational Education  
      • Informationization

  - title: Education
    layout: list
    content:
      - layout: left
        title: Xiamen University
        sub_title: PhD in Higher Education
        caption: 2023 – Present
        description: |
          Dissertation: [Working title here]
          Advisors: [Advisor names]
          Keywords: student development; academic vocational education; informationization

  - title: Publications
    layout: list
    content:
      - layout: top-middle
        title: Peer-Reviewed Articles
        description: |
          <ol>
            <li>Zhang, G., & Coauthor (Year). Title. <i>Journal Name</i>, Volume(Issue), pages. DOI</li>
          </ol>
      - layout: top-middle
        title: Conference Papers
        description: |
          <ul>
            <li>Zhang, G. (Year, Month). Paper title. <i>Conference Name</i>, City, Country.</li>
          </ul>
      - layout: top-middle
        title: Working Papers & Manuscripts
        description: |
          <ul>
            <li>Title (in preparation / under review). Target journal: ...</li>
          </ul>

  - title: Research Experience
    layout: list
    content:
      - layout: left
        title: Project Title
        sub_title: Research Assistant
        caption: YYYY – YYYY · Supervisor: [Name]
        description: |
          Methods: [survey / interviews / quasi-experiment / RCT / mixed methods]
          Responsibilities: [data collection, analysis, instrument design, literature review]
          Contribution: [1–2 impact points]

  - title: Teaching Experience
    layout: list
    content:
      - layout: left
        title: Course Name
        sub_title: Teaching Assistant / Instructor
        caption: Term, Year · Department, Xiamen University
        description: |
          Sections taught: [N]; Class size: [N].
          Topics: [list key topics].
          Evaluations: [if available].

  - title: Grants & Projects
    layout: list
    content:
      - layout: left
        title: Project Name
        caption: YYYY – YYYY · Role: PI/Co-I/RA · Funding: ¥xxx,xxx
        description: |
          Summary: [1–2 sentences on aims, methods, outcomes].
          Deliverables: [dataset / report / paper].

  - title: Invited Talks & Presentations
    layout: list
    content:
      - layout: left
        title: Talk / Workshop Title
        caption: Venue · City · Date
        description: |
          Brief description (audience, focus, materials if any).

  - title: Awards & Honors
    layout: list
    content:
      - layout: left
        title: Award Name
        caption: Issuer · Year
      - layout: left
        title: Scholarship / Fellowship
        caption: Organization · Year

  - title: Academic Service
    layout: list
    content:
      - layout: left
        title: Peer Review
        description: |
          Journals: [list if any]
      - layout: left
        title: Department/Community
        description: |
          [committee roles, student mentoring, organizing seminars]

  - title: Skills
    layout: list
    content:
      - layout: left
        title: Methods
        description: |
          Quantitative: [R, Stata, SPSS; regression, multilevel, SEM]
          Qualitative: [interviews, focus groups, coding (NVivo)]
          Mixed Methods: [design + integration]
      - layout: left
        title: Tools
        description: |
          R / Python / Stata / SPSS · NVivo · LaTeX · Git · Markdown/Jekyll
      - layout: left
        title: Languages
        description: |
          Chinese (Native); English (Fluent)

  - title: Professional Memberships
    layout: list
    content:
      - layout: left
        title: Association Name
        caption: Member · Year–Year

  - title: Profiles
    layout: list
    content:
      - layout: left
        title: Google Scholar
        link: https://scholar.google.com/citations?user=YOUR_ID
        link_text: scholar.google.com
      - layout: left
        title: ORCID
        link: https://orcid.org/0000-0000-0000-0000
        link_text: orcid.org/0000-0000-0000-0000
      - layout: left
        title: GitHub
        link: https://github.com/YOUR_USERNAME
        link_text: github.com/YOUR_USERNAME

# Footer
footer_show_references: true
references_title: "References available upon request"
