title: "张三 · 简历"
name: "张三"
email: "me@example.com"
remote_theme: sproogen/modern-resume-theme
plugins:
  - jekyll-remote-theme

darkmode: false  # 或 true/never
content:
  - title: 个人简介
    layout: text
    content: |
      3 年后端经验，擅长 Go 与云原生，负责高并发系统与服务治理。
  - title: 工作经历
    layout: list
    content:
      - layout: left
        title: 某科技
        sub_title: 高级后端工程师
        caption: 2023.07 – 至今
        description: |
          - 设计服务网关与限流，99 线延时降低 45%
          - 推动 K8s 资源治理与监控告警规范化
  - title: 教育
    layout: list
    content:
      - layout: left
        title: XX大学
        sub_title: 计算机科学 本科
        caption: 2018 – 2022
